### ISSUE TITLE
How do I run inference? 

### ISSUE THREAD

**Issue by listener17** [WaitWhatSon/nonintrusive_audio_quality_assessment_isset2023#1]
Hi!

If I want to evaluate the quality of a signal degaded.wav, which could be mono or stereo, 16 bit depth and 48 kHz sample rate audio: 

How do I run your model to get the quality score of degraded.wav?

What I don't understand is, where can I find the winning model reported in your paper? 

Any guidance in running inference with your best model will be highly appreciated. 

Thanks!

**Comment by WaitWhatSon** [comment]
Hello!

These files are too large for GitHub to store, so you can find them on Kaggle [here](https://www.kaggle.com/datasets/kaczkastudent/nonintrusive-audio-quality-assessment-isset2023)

Models and their weights files are in separate folders for each architecture and each of the 15 attempts. The VGG19-based architecture was identified as the best model based on the mean of the results.

The input data format is described in [scripts](https://github.com/WaitWhatSon/nonintrusive_audio_quality_assessment_isset2023/tree/main/scripts#spectrograms-format) under the section Spectrograms format.

I hope it is answer your question.

**Comment by listener17** [comment]
Hello @WaitWhatSon: 

Thanks, but which one of the 15 VGG-based models is your best model? 
I would expect that one needs to run "one" model to evaluate the quality.

Also, looking at https://github.com/WaitWhatSon/nonintrusive_audio_quality_assessment_isset2023/tree/main/scripts#spectrograms-format, can I evaluate the quality of arbitrary audio lengths, or can it only evaluate 10 seconds of audio?

**Comment by WaitWhatSon** [comment]
@listener17 

If you want to compare your results to ours, you should probably run all 15 models and calculate the mean. Alternatively, if you want to use just one model, the VGG19-based architecture's 5th attempt achieved the best score on objective test data, while the 11th attempt had the best score on subjective data.

The model has a fixed input size, so only 10-second audio clips can be evaluated. However, if your recording is too short, you can try looping it to extend it to 10 seconds, as we did with the subjective test data, or pad it with zeros.

**Comment by listener17** [comment]
Thanks 🙏
